### ISSUE TITLE
Kiwi bibs migration problem, URI /mapping-rules/marc-bib not valid for kiwi

### ISSUE THREAD

**Issue by cosmo-cz** [FOLIO-FSE/folio_migration_tools#166]
Running script:

> pipenv run python main.py c:\Users\user\folio-kiwi-release\migration_repo_template\mapping_files\conf.json transform_bibs

on "main" branch generates error

<pre>
2022-03-07 12:23:58,266 DEBUG   http://127.0.0.1:9130 "GET /mapping-rules/marc-bib HTTP/1.1" 404 73     connectionpool.py:452
Traceback (most recent call last):
  File "c:\Users\user\folio-kiwi-release\folio_migration_tools\main.py", line 130, in <module>
    main()
  File "c:\Users\user\folio-kiwi-release\folio_migration_tools\main.py", line 82, in main
    task_obj = task_class(task_config, library_config)
  File "c:\Users\user\folio-kiwi-release\folio_migration_tools\migration_tools\migration_tasks\bibs_transformer.py", line 68, in __init__
    self.mapper = BibsRulesMapper(self.folio_client, library_config, task_config)
  File "c:\Users\user\folio-kiwi-release\folio_migration_tools\migration_tools\marc_rules_transformation\rules_mapper_bibs.py", line 76, in __init__
    self.mappings = self.folio.folio_get_single_object(rules_endpoint)
  File "C:\Users\user\.virtualenvs\folio_migration_tools-TjPdbH38\lib\site-packages\folioclient\FolioClient.py", line 236, in folio_get_single_object
    req.raise_for_status()
  File "C:\Users\user\.virtualenvs\folio_migration_tools-TjPdbH38\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:9130/mapping-rules/marc-bib
</pre>

Using folio kiwi release and <code>c:\Users\user\folio-kiwi-release\migration_repo_template\mapping_files\conf.json</code> consists this "folioRelease" item (this is extract of conf.json file):

<pre>
{
    "libraryInformation": {
        ...
        "folioRelease": "kiwi",
    },
    ...
</pre>

Problem piece of code in <code>folio_migration_tools\migration_tools\marc_rules_transformation\rules_mapper_bibs.py</code> line 67-72:

<pre>
        logging.info("Fetching mapping rules from the tenant")
        rules_endpoint = (
            "/mapping-rules"
            if self.library_configuration.folio_release == FolioRelease.juniper
            else "/mapping-rules/marc-bib"
        )
</pre>

Strange condition which affects juniper only. Should be same for kiwi as well.

**Comment by fontanka16** [comment]
@cosmo-cz  I wonder if the issue here is something else. Can you confirm where/what the endpoint is for your marc rules by making a postman or curl call?

The code checks if Jupiter is the current version, or else it falls back to the new endpoint, that will work for kiwi and coming versions.

**Comment by cosmo-cz** [comment]
Oh, sorry. I was on wrong version of folio, it was not Kiwi as I thought. Now testing and "/mapping-rules/marc-bib" works for Kiwi. Sory once again and have a nice day.

**Comment by fontanka16** [comment]
No problem! Good luck!
