### ISSUE TITLE
Missing hrid_settings attribute causing Errors in BibsRulesMapper

### ISSUE THREAD

**Issue by jermnelson** [FOLIO-FSE/folio_migration_tools#462]
When running a BibsTransformer instance with the hrid_handling set to `preserve001`, an AttributeError is being raised when calling the `wrap_up()` method. Here is the stack trace:

```python
raceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/mapper_base.py", line 322, in store_hrid_settings
    if self.hrids_not_updated():
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/mapper_base.py", line 347, in hrids_not_updated
    self.hrid_settings["instances"]["startNumber"] == self.instance_hrid_counter
AttributeError: 'BibsRulesMapper' object has no attribute 'hrid_settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/folio/instances.py", line 101, in run_bibs_transformer
    bibs_transformer.wrap_up()
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/migration_tasks/bibs_transformer.py", line 80, in wrap_up
    self.processor.wrap_up()
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/marc_rules_transformation/marc_file_processor.py", line 246, in wrap_up
    self.mapper.wrap_up()
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py", line 209, in wrap_up
    self.store_hrid_settings()
  File "/home/airflow/.local/lib/python3.10/site-packages/folio_migration_tools/mapper_base.py", line 342, in store_hrid_settings
    f"Update them manually. {json.dumps(self.hrid_settings)}"
AttributeError: 'BibsRulesMapper' object has no attribute 'hrid_settings'
```

**Comment by branchedelac** [comment]
I am getting the same error with hrid_handling set to "default".

**Comment by fontanka16** [comment]
I believe this is a coding error. I am investigating.

**Comment by fontanka16** [comment]
@branchedelac  @jermnelson have you used the "neverUpdateHridSettings" setting in conjunction with hridHandling?

![image](https://user-images.githubusercontent.com/1894384/213021036-5e48895a-32d7-44e9-8d94-d168e67545cc.png)

**Comment by jermnelson** [comment]
@fontanka16, I started setting `neverUpdateHridSettings` to true in order to get around this error.

**Comment by fontanka16** [comment]
@jermnelson  @branchedelac  there is a PR for this now. @branchedelac  if you are able to look at it today, I could make a release before the meeting later today.
